from typing_extensions import disjoint_base

@disjoint_base
class Production:
    def __new__(cls, args: list[str], /) -> Production: ...
    async def start(self) -> None: ...
    async def scene(self) -> None: ...
    async def stop(self) -> None: ...

__all__ = ["Production"]
